# Generated by Django 5.1.2 on 2024-12-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0002_signup_student_signup_teacher_delete_sign_up_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
