# Generated by Django 5.1.2 on 2024-12-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0003_alter_signup_teacher_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup_student',
        ),
    ]
