# Generated by Django 5.1.2 on 2024-12-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0004_delete_signup_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_name', models.CharField(max_length=100)),
                ('T_mail', models.EmailField(max_length=254, unique=True)),
                ('T_subject', models.CharField(max_length=50)),
                ('T_number', models.BigIntegerField()),
            ],
        ),
    ]
