# Generated by Django 5.1.2 on 2024-12-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0005_add_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_teacher',
            new_name='addteacher',
        ),
    ]
