# Generated by Django 5.1.2 on 2024-12-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0006_rename_add_teacher_addteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=10)),
                ('fnm', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('compensation', models.IntegerField()),
                ('rollNumber', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='signup_teacher',
        ),
    ]
