# Generated by Django 5.1.2 on 2024-12-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0007_signup_delete_signup_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),
        migrations.AlterField(
            model_name='signup',
            name='fnm',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
