# Generated by Django 5.1.2 on 2024-12-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0008_remove_signup_email_alter_signup_fnm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='compensation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='rollNumber',
            field=models.IntegerField(null=True),
        ),
    ]
