# Generated by Django 5.1.2 on 2024-12-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0009_alter_signup_compensation_alter_signup_rollnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
