# Generated by Django 5.1.2 on 2024-12-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0010_signup_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_name', models.CharField(max_length=100)),
                ('S_mail', models.EmailField(max_length=254, unique=True)),
                ('S_dob', models.DateField()),
                ('S_grade', models.CharField(max_length=50)),
                ('S_number', models.BigIntegerField()),
                ('S_address', models.TextField(max_length=500)),
            ],
        ),
    ]
