# Generated by Django 5.1.2 on 2024-12-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0011_add_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_student',
            new_name='addstudent',
        ),
    ]
