# Generated by Django 5.1.4 on 2024-12-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0012_rename_add_student_addstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='fnm',
            field=models.CharField(max_length=100),
        ),
    ]
