# Generated by Django 5.1.2 on 2024-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0013_signup_email_alter_signup_fnm'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='image',
            field=models.ImageField(default=1, upload_to='\\images'),
            preserve_default=False,
        ),
    ]
