# Generated by Django 5.1.2 on 2024-12-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0014_signup_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='image',
        ),
    ]
