# Generated by Django 5.1.2 on 2024-12-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0015_remove_signup_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_location', models.CharField(max_length=200)),
                ('event_image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
