# Generated by Django 5.1.2 on 2025-01-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0016_eventbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='clubtbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_title', models.CharField(max_length=100)),
                ('pere', models.CharField(max_length=1000)),
            ],
        ),
    ]
