# Generated by Django 5.1.2 on 2025-01-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_app', '0017_clubtbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booktbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_name', models.CharField(max_length=100)),
                ('B_author', models.CharField(max_length=100)),
                ('B_image', models.ImageField(upload_to='image/books/')),
            ],
        ),
    ]
